### PR TITLE
Include build folder as part of `.gitignore`

### LINKED ISSUE #44: `build` folder is not being ignored
Build folder is not part of `.gitignore` making  `git status` output so looong
image

### PR DESCRIPTION
**Pull request by jcarranz97**
Fixes #44

### CODE REVIEW

**Comment by jcarranz97** [comment]
What do you think about this change @lurch ? :)

**Comment by lurch** [comment]
I've got no comments to make on this one, but it's not up to me to decide which PRs get merged or not.

**Comment by jcarranz97** [comment]
who is a good point of contact for this project?

**Comment by jcarranz97** [comment]
Hello @kilograham what do you think about this PR? Not sure if you are a good point of contact for this repo :)

**Review by kilograham — APPROVED** [review]

**Pull request merged**
